version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: ./deployment/backend.Dockerfile
    ports:
      - "3002:8000"
    volumes:
      - ./config.ini:/app/backend/config.ini
